version: "3.8"
services:
  rustapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 4
    networks:
      - front-network
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - rustapp
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
